### ISSUE TITLE
[Style] Only show airports at higher zoom level?

### ISSUE THREAD

**Issue by chrisballinger** [Burning-Man-Earth/iBurn-Maps#6]
Looks kind of strange to have the airports floating around over there when map is zoomed out all the way

**Comment by savannahjune** [comment]
Done. Advanced labels and the planes were angled in the correct direction. It appears one zoom level later than before, though I like the way it looks when they appear on the zoomed out version.

**Comment by chrisballinger** [comment]
@savannahjune I think we should add it back at the lower zoom level when we add more surrounding features, like the mountains and entrance road, etc

Would be awesome if we could put a backdrop watercolor version of the mountains
