### ISSUE TITLE
Bathrooms disappear and reappear at different zoom levels

### ISSUE THREAD

**Issue by chrisballinger** [Burning-Man-Earth/iBurn-Maps#7]
Caused by those darned overlap issues that I don't know if we can solve easily

**Comment by JesseCrocker** [comment]
if you add `marker-allow-overlap:true;` to the style for bathrooms they wont disappear, they'll just overlap the other markers

**Comment by chrisballinger** [comment]
We are having weird issues with TileMill not listening to our marker-allow-overlap settings. :(
